/* first */ COPY events (event_ID, event_Start, event_End, event_IsClosed, rider_ID, rider_Firstname, driver_ID, driver_Firstname, driver_Availability, timestamp_Pickup, timestamp_Dropoff, geolocation_Pickup, geolocation_Dropoff, geolocation_SurgeZone, surge_Multiplier, price, success) FROM '/Users/dillonlin/Desktop/HackReactor/Hack_Reactor/Hack_Reactor_Thesis/RydeHREventService/TenMillionEntries/firstMillion.csv' WITH DELIMITER = ',';
/* second */ COPY events (event_ID, event_Start, event_End, event_IsClosed, rider_ID, rider_Firstname, driver_ID, driver_Firstname, driver_Availability, timestamp_Pickup, timestamp_Dropoff, geolocation_Pickup, geolocation_Dropoff, geolocation_SurgeZone, surge_Multiplier, price, success) FROM '/Users/dillonlin/Desktop/HackReactor/Hack_Reactor/Hack_Reactor_Thesis/RydeHREventService/TenMillionEntries/secondMillion.csv' WITH DELIMITER = ',';
/* third */ COPY events (event_ID, event_Start, event_End, event_IsClosed, rider_ID, rider_Firstname, driver_ID, driver_Firstname, driver_Availability, timestamp_Pickup, timestamp_Dropoff, geolocation_Pickup, geolocation_Dropoff, geolocation_SurgeZone, surge_Multiplier, price, success) FROM '/Users/dillonlin/Desktop/HackReactor/Hack_Reactor/Hack_Reactor_Thesis/RydeHREventService/TenMillionEntries/thirdMillion.csv' WITH DELIMITER = ',';
/* fourth */ COPY events (event_ID, event_Start, event_End, event_IsClosed, rider_ID, rider_Firstname, driver_ID, driver_Firstname, driver_Availability, timestamp_Pickup, timestamp_Dropoff, geolocation_Pickup, geolocation_Dropoff, geolocation_SurgeZone, surge_Multiplier, price, success) FROM '/Users/dillonlin/Desktop/HackReactor/Hack_Reactor/Hack_Reactor_Thesis/RydeHREventService/TenMillionEntries/fourthMillion.csv' WITH DELIMITER = ',';
/* fifth */ COPY events (event_ID, event_Start, event_End, event_IsClosed, rider_ID, rider_Firstname, driver_ID, driver_Firstname, driver_Availability, timestamp_Pickup, timestamp_Dropoff, geolocation_Pickup, geolocation_Dropoff, geolocation_SurgeZone, surge_Multiplier, price, success) FROM '/Users/dillonlin/Desktop/HackReactor/Hack_Reactor/Hack_Reactor_Thesis/RydeHREventService/TenMillionEntries/fifthMillion.csv' WITH DELIMITER = ',';
/* sixth */ COPY events (event_ID, event_Start, event_End, event_IsClosed, rider_ID, rider_Firstname, driver_ID, driver_Firstname, driver_Availability, timestamp_Pickup, timestamp_Dropoff, geolocation_Pickup, geolocation_Dropoff, geolocation_SurgeZone, surge_Multiplier, price, success) FROM '/Users/dillonlin/Desktop/HackReactor/Hack_Reactor/Hack_Reactor_Thesis/RydeHREventService/TenMillionEntries/sixthMillion.csv' WITH DELIMITER = ',';
/* seventh */ COPY events (event_ID, event_Start, event_End, event_IsClosed, rider_ID, rider_Firstname, driver_ID, driver_Firstname, driver_Availability, timestamp_Pickup, timestamp_Dropoff, geolocation_Pickup, geolocation_Dropoff, geolocation_SurgeZone, surge_Multiplier, price, success) FROM '/Users/dillonlin/Desktop/HackReactor/Hack_Reactor/Hack_Reactor_Thesis/RydeHREventService/TenMillionEntries/seventhMillion.csv' WITH DELIMITER = ',';
/* eigth */ COPY events (event_ID, event_Start, event_End, event_IsClosed, rider_ID, rider_Firstname, driver_ID, driver_Firstname, driver_Availability, timestamp_Pickup, timestamp_Dropoff, geolocation_Pickup, geolocation_Dropoff, geolocation_SurgeZone, surge_Multiplier, price, success) FROM '/Users/dillonlin/Desktop/HackReactor/Hack_Reactor/Hack_Reactor_Thesis/RydeHREventService/TenMillionEntries/eigthMillion.csv' WITH DELIMITER = ',';
/* ninth */ COPY events (event_ID, event_Start, event_End, event_IsClosed, rider_ID, rider_Firstname, driver_ID, driver_Firstname, driver_Availability, timestamp_Pickup, timestamp_Dropoff, geolocation_Pickup, geolocation_Dropoff, geolocation_SurgeZone, surge_Multiplier, price, success) FROM '/Users/dillonlin/Desktop/HackReactor/Hack_Reactor/Hack_Reactor_Thesis/RydeHREventService/TenMillionEntries/ninthMillion.csv' WITH DELIMITER = ',';
/* tenth */ COPY events (event_ID, event_Start, event_End, event_IsClosed, rider_ID, rider_Firstname, driver_ID, driver_Firstname, driver_Availability, timestamp_Pickup, timestamp_Dropoff, geolocation_Pickup, geolocation_Dropoff, geolocation_SurgeZone, surge_Multiplier, price, success) FROM '/Users/dillonlin/Desktop/HackReactor/Hack_Reactor/Hack_Reactor_Thesis/RydeHREventService/TenMillionEntries/tenthMillion.csv' WITH DELIMITER = ',';

/* One Time Analytics Load */ COPY events (event_ID, event_Start, surge_Multiplier) FROM '/Users/dillonlin/Desktop/HackReactor/Hack_Reactor/Hack_Reactor_Thesis/RydeHREventService/TenMillionEntriesAnalytics/firstMillion.csv' WITH DELIMITER = ',';